# Generated by Django 5.1 on 2024-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0002_friendship_last_connection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
