# Generated by Django 5.1 on 2024-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0006_remove_invitation_accepted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.AddField(
            model_name="message",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio_messages/"),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("audio", "Audio")],
                default="text",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
