# Generated by Django 5.1 on 2024-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0008_friend_last_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="image_messages/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("audio", "Audio"), ("image", "Images")],
                default="text",
                max_length=5,
            ),
        ),
    ]
